# Write your MySQL query statement below
SELECT NAME,IFNULL(SUM(DISTANCE),0) AS TRAVELLED_DISTANCE 
FROM Users LEFT JOIN Rides ON
USERS.ID=RIDES.USER_ID GROUP BY RIDES.USER_ID 
ORDER BY TRAVELLED_DISTANCE DESC, NAME;