# Write your MySQL query statement below
SELECT ROUND(
    (SUM(CASE WHEN DATE_ADD(TEMP.FIRSTLOGIN,INTERVAL 1 DAY) = A.EVENT_DATE THEN 1 ELSE 0 END))/COUNT(DISTINCT(A.PLAYER_ID)),2) AS FRACTION FROM 
(SELECT PLAYER_ID,MIN(EVENT_DATE) AS FIRSTLOGIN FROM ACTIVITY GROUP BY PLAYER_ID) AS TEMP
JOIN
ACTIVITY A ON A.PLAYER_ID=TEMP.PLAYER_ID;